# Generated by Django 3.1.4 on 2021-03-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=25)),
                ('slug', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
