# Generated by Django 3.1.4 on 2021-03-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whispme', '0003_postcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='parent',
        ),
    ]
